# Generated by Django 5.1.7 on 2025-04-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='model',
            new_name='modelo',
        ),
    ]
